const input = document.getElementById("user-input");

// Send message on Enter key
input.addEventListener("keydown", function (event) {
  if (event.key === "Enter") {
    event.preventDefault(); // prevent newline / form submit
    sendMessage();
  }
});

function sendMessage() {
  const text = input.value.trim();
  if (!text) return;

  addMessage(text, "user");
  input.value = "";

  // Simulated Gemini reply
  setTimeout(() => {
    addMessage(
      "This response is generated by Gemini. " +
      "Once connected to the Gemini API, I will answer in real time.",
      "gemini"
    );
  }, 800);
}

function addMessage(text, sender) {
  const chatBox = document.getElementById("chat-box");
  const msg = document.createElement("div");
  msg.className = `message ${sender}`;
  msg.textContent = text;
  chatBox.appendChild(msg);
  chatBox.scrollTop = chatBox.scrollHeight;
}
